apiVersion: v1
kind: Service
metadata:
  name: greeting
  labels:
    name: greeting
    {{- template "labels" . }}
spec:
  selector:
    app: greeting
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
  - name: debug
    protocol: TCP
    port: {{ .Values.service.externalDebugPort }}
    targetPort: {{ .Values.service.internalDebugPort }}
